import * as images from './images';

const attacksMatrix = {
    claws: {
        name: 'claws',
        type: 'cutting',
        range: 'close',
        icon: images['claws'],
        cooldown: 3,
    },
    bite: {
        name: 'bite',
        type: 'cutting',
        icon: images['bite'],
        range: 'close',
        cooldown: 3,
        effect: { type: 'bleed', chance: 40, duration: 5 }
    },
    crush: {
        name: 'crush',
        type: 'crushing',
        icon: images['crushing'],
        range: 'close',
        cooldown: 5,
        effect: { type: 'stun', chance: 40, duration: 5 }
    },
    tackle: {
        name: 'tackle',
        type: 'crushing',
        icon: images['tackle'],
        range: 'close',
        cooldown: 4,
        effect: { type: 'stun', chance: 30, duration: 3 }
    },
    grasp: {
        name: 'grasp',
        type: 'crushing',
        icon: images['grasp'],
        isGif: true,
        range: 'close',
        cooldown: 3,
        effect: { type: 'stun', chance: 20, duration: 2 },
    },
    energy_drain: {
        name: 'energy drain',
        type: 'curse',
        icon: images['energy_drain'],
        range: 'medium',
        cooldown: 3,
        effect: { type: 'energy drain', chance: 100, duration: 4 },
    },
    fire_breath: {
        name: 'fire breath',
        type: 'fire',
        icon: images['fire_breath'],
        range: 'medium',
        cooldown: 3,
    },
    void_lance: {
        name: 'void lance',
        icon: images['void_lance'],
        type: 'psionic',
        range: 'medium',
        cooldown: 3,
    },
    energy_blast: {
        name: 'energy blast',
        type: 'arcane',
        range: 'far',
        icon: images['void_lance'],
        cooldown: 6,
    },
    lightning: {
        name: 'lightning',
        type: 'electricity',
        icon: images['lightning'],
        range: 'far',
        cooldown: 3,
    },
    sword_swing: {
        name: 'sword swing',
        type: 'cutting',
        range: 'close',
        icon: images['sword'],
        cooldown: 2,
    },
    sword_thrust: {
        name: 'sword thrust',
        type: 'cutting',
        range: 'close',
        icon: images['sword'],
        cooldown: 2,
    },
    dragon_punch: {
        name: 'dragon punch',
        type: 'crushing',
        range: 'close',
        icon: images['hand_7'],
        cooldown: 3,
    },
    meditate: {
        name: 'meditate',
        type: 'buff',
        range: 'self',
        icon: images['buckler'],
        cooldown: 3,
    },
    heal: {
        name: 'heal',
        type: 'buff',
        range: 'close',
        icon: images['buckler'],
        cooldown: 3,
    },
    fire_arrow: {
        name: 'fire arrow',
        type: 'fire',
        range: 'far',
        icon: images['bow_and_arrow'],
        cooldown: 2,
    },
    axe_throw: {
        name: 'axe throw',
        type: 'cutting',
        range: 'medium',
        icon: images['axe'],
        cooldown: 2,
    },
    axe_swing: {
        name: 'axe swing',
        type: 'cutting',
        range: 'close',
        icon: images['axe'],
        cooldown: 1,
    },
    spear_throw: {
        name: 'spear throw',
        type: 'cutting',
        range: 'far',
        icon: images['spear'],
        cooldown: 3.2,
    },
    flying_lotus: {
        name: 'flying lotus',
        type: 'crushing',
        range: 'medium',
        icon: images['scepter'],
        cooldown: 4.5,
    },
    shield_bash: {
        name: 'shield bash',
        type: 'crushing',
        range: 'close',
        icon: images['buckler'],
        cooldown: 4.5,
    },
    cane_strike: {
        name: 'cane strike',
        type: 'crushing',
        range: 'far',
        icon: images['scepter'],
        cooldown: 3,
    },
    dagger_stab: {
        name: 'dagger_stab',
        type: 'cutting',
        range: 'close',
        icon: images['sword'],
        cooldown: 2,
    },
    snake_strike: {
        name: 'snake_strike',
        type: 'cutting',
        range: 'medium',
        icon: images['sword'],
        cooldown: 2,
    }
};

export default attacksMatrix;
