import * as images from './images';

const skillsMatrix = {
    // === RANGER ===
    keen_eye: {
        class: 'ranger',
        id: 'keen_eye',
        tier: 1,
        name: 'Keen Eye',
        desc: 'L1: Reveals +2 fog tiles. L2: Reveals nearby traps. L3: +3 DEX to trap saves.',
        icon: images.eagle_eye,
        cooldown: 0,
        type: 'passive',
        treePath: 'global',
        isPassive: true,
        knownByDefault: true
    },
    hunters_quarry: {
        class: 'ranger',
        id: 'hunters_quarry',
        tier: 2,
        name: "Hunter's Quarry",
        desc: '+10% food drop on monster defeat.',
        icon: images.ranger_mark,
        cooldown: 0,
        type: 'passive',
        treePath: 'global',
        isPassive: true,
        knownByDefault: false
    },
    read_the_land: {
        class: 'ranger',
        id: 'read_the_land',
        tier: 2,
        name: 'Read the Land',
        desc: 'Adjacent tile types hinted on entry.',
        icon: images.eye,
        cooldown: 0,
        type: 'passive',
        treePath: 'global',
        isPassive: true,
        knownByDefault: false
    },
    trailblaze: {
        class: 'ranger',
        id: 'trailblaze',
        tier: 3,
        name: 'Trailblaze',
        desc: 'Visual breadcrumb to last camp spot.',
        icon: images.camp,
        cooldown: 0,
        type: 'passive',
        treePath: 'global',
        isPassive: true,
        knownByDefault: false
    },
    scrounging_rat: {
        class: 'ranger',
        id: 'scrounging_rat',
        tier: 3,
        name: 'Scrounging Rat',
        desc: 'Forage for food in camp: 15-30 food (3h) / 30-50 food (2h) / 50-80 food (1h).',
        icon: images.scrounging_rat,
        cooldown: 0,
        type: 'passive',
        treePath: 'global',
        isPassive: true,
        knownByDefault: false
    },
    fastidious_crow: {
        class: 'ranger',
        id: 'fastidious_crow',
        tier: 4,
        name: 'Fastidious Crow',
        desc: 'Scout a 10x10 board area for 24h. Process: 20m. Cooldown: 6h / 3h. Reward: 5-20g / 25-80g + 30% shard chance.',
        icon: images.fastidious_crow,
        cooldown: 0,
        type: 'passive',
        treePath: 'global',
        isPassive: true,
        knownByDefault: false
    },
    notch: {
        class: 'ranger',
        treePath: 'combat_a',
        id: 'notch',
        tier: 1,
        knownByDefault: true,
        name: 'Notch',
        desc: 'Select arrow type to load.',
        icon: images['ranger_notch'],
        cooldown: 0,
        duration: 'instant',
        range: 'self',
        type: 'utility'
    },
    loose: {
        class: 'ranger',
        treePath: 'combat_a',
        id: 'loose',
        tier: 1,
        knownByDefault: true,
        name: 'Loose',
        desc: 'Shoot the selected notched arrow.',
        icon: images['ranger_loose'],
        cooldown: 2,
        duration: 'instant',
        range: 'far',
        atkPercentage: 100,
        type: 'damage'
    },
    mark: {
        class: 'ranger',
        treePath: 'combat_b',
        id: 'mark',
        tier: 1,
        knownByDefault: true,
        name: 'Mark',
        desc: 'Place a target mark on the enemy.',
        icon: images['ranger_mark'],
        cooldown: 6,
        duration: 'long',
        range: 'far',
        type: 'debuff',
        effect: ['target_marked']
    },
    execute: {
        class: 'ranger',
        treePath: 'combat_a',
        id: 'execute',
        tier: 3,
        name: 'Execute',
        desc: 'fires a single devastating arrow for 300% attack',
        icon: images['ranger_execute'],
        cooldown: 10,
        duration: 'instant',
        range: 'far',
        atkPercentage: 300,
        type: 'damage'
    },
    burst_shot: {
        class: 'ranger',
        treePath: 'combat_a',
        id: 'burst_shot',
        tier: 3,
        name: 'Burst Shot',
        desc: 'Shoot three arrows in rapid succession.',
        icon: images['ranger_burst_shot'],
        cooldown: 10,
        duration: 'instant',
        range: 'far',
        atkPercentage: 100,
        type: 'damage'
    },
    burst_attack: {
        class: 'ranger',
        treePath: 'combat_a',
        id: 'burst_attack',
        tier: 3,
        name: 'Burst Attack',
        desc: 'Shoot three arrows in rapid succession.',
        icon: images['ranger_burst_shot'],
        cooldown: 10,
        duration: 'instant',
        range: 'far',
        atkPercentage: 100,
        type: 'damage'
    },
    ensnare: {
        class: 'ranger',
        treePath: 'combat_b',
        id: 'ensnare',
        tier: 2,
        name: 'Ensnare',
        desc: 'Entangle the target, paralyzing them.',
        icon: images['ranger_ensnare'],
        cooldown: 6,
        duration: 'short',
        range: 'medium',
        type: 'debuff',
        effect: { type: 'ensnared', chance: 80, duration: 'short' }
    },
    eagle_eye: {
        class: 'ranger',
        treePath: 'combat_b',
        id: 'eagle_eye',
        tier: 1,
        knownByDefault: true,
        name: 'Eagle Eye',
        desc: 'Passive: Whenever an enemy unit is summoned on the battlefield, immediately shoot two randomly chosen arrows at it.',
        icon: images['eagle_eye'],
        cooldown: 0,
        duration: 'instant',
        range: 'far',
        type: 'passive',
        isPassive: true
    },

    // === SAGE ===
    herbalism: {
        class: 'sage',
        id: 'herbalism',
        tier: 1,
        name: 'Herbalism',
        desc: 'Camp costs 1 less food per member.',
        icon: images.herbalism_sage,
        cooldown: 0,
        type: 'passive',
        treePath: 'global',
        isPassive: true,
        knownByDefault: true
    },
    mend: {
        class: 'sage',
        id: 'mend',
        tier: 2,
        name: 'Mend',
        desc: 'Out-of-combat potions restore +15% HP.',
        icon: images.healing_hands || images.avatar,
        cooldown: 0,
        type: 'passive',
        treePath: 'global',
        isPassive: true,
        knownByDefault: false
    },
    ritual_efficiency: {
        class: 'sage',
        id: 'ritual_efficiency',
        tier: 3,
        name: 'Ritual Efficiency',
        desc: 'Ritual prep time -25%.',
        icon: images.ritual_efficiency_sage,
        cooldown: 0,
        type: 'passive',
        treePath: 'global',
        isPassive: true,
        knownByDefault: false
    },
    awake_refreshed_sage: {
        class: 'sage',
        id: 'awake_refreshed',
        tier: 3,
        name: 'Awake Refreshed',
        desc: 'Camp recuperation grants an additional +10/+20/+40 Resolve.',
        icon: images.awake_refreshed_sage,
        cooldown: 0,
        type: 'passive',
        treePath: 'global',
        isPassive: true,
        knownByDefault: false
    },
    revive: {
        class: 'sage',
        id: 'revive',
        tier: 4,
        name: 'Revive',
        desc: 'Once per run: fallen member revived at 25% HP.',
        icon: images.revive_sage,
        cooldown: 0,
        type: 'passive',
        treePath: 'global',
        isPassive: true,
        knownByDefault: false
    },
    heal: {
        class: 'sage',
        treePath: 'combat_a',
        id: 'heal',
        tier: 1,
        knownByDefault: true,
        name: 'Heal',
        desc: 'Restore 30 HP to an ally.',
        icon: images['healing_hands'],
        cooldown: 2,
        initialCooldown: 1,
        duration: 'instant',
        range: 'close',
        type: 'heal',
        flatDamage: -30, // negative damage is healing
        regeneration_percent: 30
    },
    circle_of_protection: {
        class: 'sage',
        treePath: 'combat_a',
        id: 'circle_of_protection',
        tier: 1,
        knownByDefault: true,
        name: 'Circle of Protection',
        desc: 'Create a sanctuary that increases the Defense of all allies within a 2.25-tile radius by 15 for 6 rounds.',
        icon: images['circle_of_protection'],
        cooldown: 12,
        duration: 'long',
        range: 'self',
        type: 'buff',
        effect: ['buff_self'],
        buff: {
            increase_stats: {
                stats: ['def'],
                amounts: [15]
            }
        }
    },
    invigorate: {
        class: 'sage',
        treePath: 'combat_a',
        id: 'invigorate',
        tier: 2,
        name: 'Invigorate',
        desc: 'Create a sanctuary that restores 20% Stamina to all allies within a 2.25-tile radius each round. Lasts 3 rounds.',
        icon: images['invigorate'],
        cooldown: 10,
        initialCooldown: 2,
        duration: 'short',
        range: 'self',
        type: 'buff',
        effect: ['buff_self']
    },
    perceive: {
        class: 'sage',
        treePath: 'combat_b',
        id: 'perceive',
        tier: 2,
        name: 'Perceive',
        desc: 'Doubles the weakness of each enemy.',
        icon: images['perceive'],
        cooldown: 12,
        duration: '2x-long',
        range: 'far',
        type: 'debuff',
        effect: ['weakness_doubled']
    },
    circle_of_deflection: {
        class: 'sage',
        treePath: 'combat_b',
        id: 'circle_of_deflection',
        tier: 3,
        name: 'Circle of Deflection',
        desc: 'A teal runic barrier that gives allies inside a 50% chance to reflect ranged attacks back at the attacker.',
        icon: images['circle_of_deflection'],
        cooldown: 14,
        duration: 'long',
        range: 'self',
        type: 'buff',
        effect: ['buff_self'],
        buff: {}
    },
    direct_dispel: {
        class: 'sage',
        treePath: 'combat_a',
        id: 'direct_dispel',
        tier: 3,
        name: 'Direct Dispel',
        desc: 'Removes all debuffs from a friendly unit.',
        icon: images.direct_dispel,
        cooldown: 10,
        initialCooldown: 3,
        duration: 'instant',
        range: 'medium',
        type: 'utility'
    },

    // === SOLDIER ===
    fortify: {
        class: 'soldier',
        id: 'fortify',
        tier: 1,
        name: 'Fortify',
        desc: 'Resolve does not decay while camping.',
        icon: images.shield_wall,
        cooldown: 0,
        type: 'passive',
        treePath: 'global',
        isPassive: true,
        knownByDefault: true
    },
    breacher: {
        class: 'soldier',
        id: 'breacher',
        tier: 2,
        name: 'Breacher',
        desc: 'Force open a Minor Key gate once per level.',
        icon: images.breacher_soldier,
        cooldown: 0,
        type: 'passive',
        treePath: 'global',
        isPassive: true,
        knownByDefault: false
    },
    rally: {
        class: 'soldier',
        id: 'rally',
        tier: 2,
        name: 'Rally',
        desc: '+5 bonus Resolve on combat victory.',
        icon: images.rally_soldier,
        cooldown: 0,
        type: 'passive',
        treePath: 'global',
        isPassive: true,
        knownByDefault: false
    },
    iron_will: {
        class: 'soldier',
        id: 'iron_will',
        tier: 3,
        name: 'Iron Will',
        desc: 'Party Resolve never drops below 20 from deaths.',
        icon: images.iron_will_soldier,
        cooldown: 0,
        type: 'passive',
        treePath: 'global',
        isPassive: true,
        knownByDefault: false
    },
    awake_refreshed_soldier: {
        class: 'soldier',
        id: 'awake_refreshed',
        tier: 3,
        name: 'Awake Refreshed',
        desc: 'Camp recuperation grants an additional +10/+20/+40 Resolve.',
        icon: images.awake_refreshed_soldier,
        cooldown: 0,
        type: 'passive',
        treePath: 'global',
        isPassive: true,
        knownByDefault: false
    },
    strong_resolve_soldier: {
        class: 'soldier',
        id: 'strong_resolve',
        tier: 4,
        name: 'Strong Resolve',
        desc: 'Reduces Resolve penalties by 40%/75%/90%.',
        icon: images.strong_resolve_soldier,
        cooldown: 0,
        type: 'passive',
        treePath: 'global',
        isPassive: true,
        knownByDefault: false
    },
    slash: {
        class: 'soldier',
        treePath: 'combat_b',
        id: 'slash',
        tier: 1,
        knownByDefault: true,
        name: 'Slash',
        desc: 'Execute a heavy steel blade slash.',
        icon: images['soldier_slash'],
        cooldown: 1,
        duration: 'instant',
        range: 'close',
        atkPercentage: 100,
        type: 'damage'
    },
    shield_wall: {
        class: 'soldier',
        treePath: 'combat_a',
        id: 'shield_wall',
        tier: 2,
        name: 'Shield Wall',
        desc: 'Deploy a protective energetic wall overlay.',
        icon: images['shield_wall'],
        cooldown: 12,
        duration: 'long',
        range: 'self',
        type: 'buff'
    },
    shield_slam: {
        class: 'soldier',
        treePath: 'combat_a',
        id: 'shield_slam',
        tier: 1,
        knownByDefault: true,
        name: 'Shield Slam',
        desc: 'Ram target to cause stun. Double damage if wielding a shield.',
        icon: images['shield_slam'],
        cooldown: 4,
        duration: 'instant',
        range: 'close',
        atkPercentage: 100,
        type: 'damage',
        effect: { type: 'stun', chance: 100, duration: 1 }
    },
    defensive_stance: {
        class: 'soldier',
        treePath: 'combat_a',
        id: 'defensive_stance',
        tier: 2,
        name: 'Defensive Stance',
        desc: 'Adopt a defensive stance to absorb damage.',
        icon: images['soldier_defensive_stance'],
        cooldown: 6,
        duration: 'short',
        range: 'self',
        type: 'buff',
        effect: ['buff_self'],
        buff: {
            increase_stats: {
                stats: ['def'],
                amounts: [10]
            }
        }
    },
    fist_of_honor: {
        class: 'soldier',
        treePath: 'combat_b',
        id: 'fist_of_honor',
        tier: 1,
        knownByDefault: true,
        name: 'Fist of Honor',
        desc: 'Strike with a fist of pure honor, stunning the target for 2 rounds.',
        icon: images['soldier_fist_of_honor'],
        cooldown: 4,
        initial: 3,
        duration: 'instant',
        range: 'close',
        atkPercentage: 100,
        type: 'damage',
        effect: { type: 'stun', chance: 80, duration: 2 }
    },
    imbued_strike: {
        class: 'soldier',
        treePath: 'combat_b',
        id: 'imbued_strike',
        tier: 1,
        knownByDefault: true,
        name: 'Imbued Strike',
        desc: 'Strike with an energy-imbued blade dealing 200% attack damage.',
        icon: images['soldier_imbued_strike'],
        cooldown: 4,
        duration: 'instant',
        range: 'close',
        type: 'damage',
        atkPercentage: 200
    },
    one_man_army: {
        class: 'soldier',
        treePath: 'combat_b',
        id: 'one_man_army',
        tier: 4,
        name: 'One Man Army',
        desc: 'Summon the strength of a one-man army.',
        icon: images['soldier_one_man_army'],
        cooldown: 16,
        duration: 'long',
        range: 'self',
        type: 'buff',
        effect: ['buff_self'],
        buff: {
            increase_stats: {
                stats: ['atk', 'def'],
                amounts: [10, 10]
            }
        }
    },
    inspire: {
        class: 'soldier',
        treePath: 'combat_a',
        id: 'inspire',
        tier: 3,
        name: 'Inspire',
        desc: 'Inspire nearby allies to fight harder. Inspired units always succeed resolve checks and replenish 10% stamina each round.',
        icon: images['inspire'],
        cooldown: 10,
        duration: 'long',
        range: 'medium',
        type: 'buff',
        effect: ['buff_allies']
    },
    battlecry: {
        class: 'soldier',
        treePath: 'combat_a',
        id: 'battlecry',
        tier: 3,
        name: 'Battlecry',
        desc: 'Unleash a roar, amplifying size and damage.',
        icon: images['soldier_battlecry'],
        cooldown: 10,
        duration: 'short',
        range: 'self',
        type: 'buff',
        effect: ['buff_self'],
        buff: {
            increase_stats: {
                stats: ['atk'],
                amounts: [8]
            }
        }
    },

    // === WIZARD ===
    arcane_sense: {
        class: 'wizard',
        id: 'arcane_sense',
        tier: 1,
        name: 'Arcane Sense',
        desc: 'Magically read a chest\'s contents — reveals its tier and quality before you open it.',
        icon: images.arcane_sense_wizard,
        cooldown: 0,
        type: 'passive',
        treePath: 'global',
        isPassive: true,
        knownByDefault: true
    },
    ley_tap: {
        class: 'wizard',
        id: 'ley_tap',
        tier: 2,
        name: 'Ley Tap',
        desc: 'Draw energy at Magic Nexus — recover 15% endurance.',
        icon: images.ley_tap_wizard,
        cooldown: 0,
        type: 'passive',
        treePath: 'global',
        isPassive: true,
        knownByDefault: false
    },
    dimensional_pocket: {
        class: 'wizard',
        id: 'dimensional_pocket',
        tier: 3,
        name: 'Dimensional Pocket',
        desc: '+2 shared inventory slots.',
        icon: images.dimensional_pocket_wizard,
        cooldown: 0,
        type: 'passive',
        treePath: 'global',
        isPassive: true,
        knownByDefault: false
    },
    scry: {
        class: 'wizard',
        id: 'scry',
        tier: 4,
        name: 'Scry',
        desc: 'Reveals all chests and monsters for 30s once per run.',
        icon: images.scry_wizard,
        cooldown: 0,
        type: 'passive',
        treePath: 'global',
        isPassive: true,
        knownByDefault: false
    },
    fireball: {
        class: 'wizard',
        treePath: 'combat_a',
        id: 'fireball',
        tier: 1,
        knownByDefault: true,
        name: 'Fireball',
        desc: 'Launch an explosive orb of flame.',
        icon: images['fireball'],
        cooldown: 4,
        duration: 'instant',
        range: 'far',
        atkPercentage: 100,
        type: 'damage',
        flatDamage: 15
    },
    ice_blast: {
        class: 'wizard',
        treePath: 'combat_b',
        id: 'ice_blast',
        tier: 1,
        knownByDefault: true,
        name: 'Ice Blast',
        desc: 'Freeze target in a block of absolute-zero ice.',
        icon: images['ice_blast_icon'],
        cooldown: 12,
        duration: 'short',
        range: 'medium',
        atkPercentage: 100,
        type: 'debuff damage',
        flatDamage: 10,
        effect: { type: 'frozen', chance: 80, duration: 'short' }
    },
    magic_missile: {
        class: 'wizard',
        treePath: 'combat_b',
        id: 'magic_missile',
        tier: 1,
        knownByDefault: true,
        name: 'Magic Missile',
        desc: 'Fire three seeking missiles in sequence.',
        icon: images['magic_missile_icon'],
        cooldown: 2,
        duration: 'instant',
        range: 'far',
        atkPercentage: 10,
        type: 'damage',
        flatDamage: 5
    },
    lightning_strike: {
        class: 'wizard',
        treePath: 'combat_a',
        id: 'lightning_strike',
        tier: 2,
        name: 'Lightning',
        desc: 'Strike the target with electrical charge.',
        icon: images['lightning'],
        cooldown: 6,
        duration: 'instant',
        range: 'far',
        atkPercentage: 100,
        type: 'damage',
        flatDamage: 22
    },
    acid_blast: {
        class: 'wizard',
        treePath: 'combat_a',
        id: 'acid_blast',
        tier: 2,
        name: 'Acid Blast',
        desc: 'Conical green projectile that poisons the target.',
        icon: images['wizard_acid_blast'],
        cooldown: 4,
        duration: 'short',
        range: 'medium',
        atkPercentage: 100,
        type: 'debuff damage',
        flatDamage: 12,
        effect: { type: 'poison', chance: 100, duration: 'short' }
    },
    disintegrate: {
        class: 'wizard',
        treePath: 'combat_a',
        id: 'disintegrate',
        tier: 3,
        name: 'Disintegrate',
        desc: 'Call a white-red beam that expands and shakes target.',
        icon: images['wizard_disintegrate'],
        cooldown: 8,
        duration: 'instant',
        range: 'medium',
        atkPercentage: 100,
        type: 'damage',
        flatDamage: 30
    },
    sleep: {
        class: 'wizard',
        treePath: 'combat_b',
        id: 'sleep',
        tier: 2,
        name: 'Sleep',
        desc: 'Cast a soothing spell that puts the target to sleep. Broken by damage.',
        icon: images['wizard_sleep'],
        cooldown: 10,
        duration: 'long',
        range: 'medium',
        type: 'debuff',
        mentalityDebuff: true,
        power: 40,
        effect: { type: 'sleep', duration: '2x-long' }
    },
    annihilation: {
        class: 'wizard',
        treePath: 'combat_a',
        id: 'annihilation',
        tier: 3,
        name: 'Annihilation',
        desc: 'Unleash a devastating burst of pure energy.',
        icon: images['wizard_annihilation'],
        cooldown: 14,
        duration: 'instant',
        range: 'far',
        atkPercentage: 100,
        type: 'damage',
        flatDamage: 40
    },
    vortex: {
        class: 'wizard',
        treePath: 'combat_b',
        id: 'vortex',
        tier: 4,
        name: 'Vortex',
        desc: 'Create a swirling maelstrom at the target location.',
        icon: images['wizard_vortex'],
        cooldown: 8,
        duration: 'short',
        range: 'medium',
        type: 'debuff'
    },

    // === BARBARIAN ===
    iron_gut: {
        class: 'barbarian',
        id: 'iron_gut',
        tier: 1,
        name: 'Iron Gut',
        desc: 'Barbarian does not count toward camping food cost.',
        icon: images.iron_gut_barbarian,
        cooldown: 0,
        type: 'passive',
        treePath: 'global',
        isPassive: true,
        knownByDefault: true
    },
    savage_haul: {
        class: 'barbarian',
        id: 'savage_haul',
        tier: 2,
        name: 'Savage Haul',
        desc: 'Grants +2/+4/+6 Strength and +10/+20/+30 Max HP.',
        icon: images.savage_haul_barbarian,
        cooldown: 0,
        type: 'passive',
        treePath: 'global',
        isPassive: true,
        knownByDefault: false
    },
    bloodhound: {
        class: 'barbarian',
        id: 'bloodhound',
        tier: 3,
        name: 'Bloodhound',
        desc: 'Reveals all monsters on miniboard entry.',
        icon: images.bloodhound_barbarian,
        cooldown: 0,
        type: 'passive',
        treePath: 'global',
        isPassive: true,
        knownByDefault: false
    },
    endure: {
        class: 'barbarian',
        id: 'endure',
        tier: 4,
        name: 'Endure',
        desc: 'Zero-food camp: no Resolve penalty, crew heals to 50%.',
        icon: images.endure_barbarian,
        cooldown: 0,
        type: 'passive',
        treePath: 'global',
        isPassive: true,
        knownByDefault: false
    },
    barbarian_slash: {
        class: 'barbarian',
        treePath: 'combat_a',
        id: 'barbarian_slash',
        tier: 1,
        knownByDefault: true,
        name: 'Slash',
        desc: 'Execute a fast horizontal slash.',
        icon: images['barbarian_slash'],
        cooldown: 1,
        duration: 'instant',
        range: 'close',
        atkPercentage: 100,
        type: 'damage'
    },
    barbarian_cleave: {
        class: 'barbarian',
        treePath: 'combat_a',
        id: 'barbarian_cleave',
        tier: 1,
        knownByDefault: true,
        name: 'Cleave',
        desc: 'Crush target skull with axe, causing bleed.',
        icon: images['barbarian_cleave'],
        cooldown: 4,
        duration: 'short',
        range: 'close',
        atkPercentage: 100,
        type: 'damage',
        effect: { type: 'bleed', chance: 100, duration: 'short' }
    },
    barbarian_axe_throw: {
        class: 'barbarian',
        treePath: 'combat_a',
        id: 'barbarian_axe_throw',
        tier: 2,
        name: 'Axe Throw',
        desc: 'Hurl a spinning axe at the target.',
        icon: images['barbarian_axe_throw'],
        cooldown: 2,
        duration: 'instant',
        range: 'medium',
        atkPercentage: 100,
        type: 'damage'
    },
    barbarian_berserker: {
        class: 'barbarian',
        treePath: 'combat_b',
        id: 'barbarian_berserker',
        tier: 1,
        knownByDefault: true,
        name: 'Berserker',
        desc: 'Enter a state of absolute fury: +12 Attack, doubles movement/attack speed (halves cooldowns) for 1 turn cycle, cleanses Fear and grants Fear immunity.',
        icon: images['barbarian_berserker'],
        cooldown: 12,
        duration: 'long',
        range: 'self',
        type: 'buff',
        effect: ['buff_self'],
        buff: {
            increase_stats: {
                stats: ['atk'],
                amounts: [12]
            }
        }
    },
    barbarian_leap_attack: {
        class: 'barbarian',
        treePath: 'combat_b',
        id: 'barbarian_leap_attack',
        tier: 2,
        name: 'Leap Attack',
        desc: 'Leap onto target, knocking back and stunning.',
        icon: images['barbarian_leap_attack'],
        cooldown: 8,
        initialCooldown: 1,
        duration: 'short',
        range: 'far',
        atkPercentage: 100,
        type: 'damage',
        effect: { type: 'stun', chance: 100, duration: 'short' }
    },
    barbarian_whirlwind: {
        class: 'barbarian',
        treePath: 'combat_b',
        id: 'barbarian_whirlwind',
        tier: 2,
        name: 'Whirlwind',
        desc: 'Attack all adjacent units with a spinning vortex.',
        icon: images['monk_whirlwind'],
        cooldown: 6,
        duration: 'instant',
        range: 'close',
        atkPercentage: 100,
        type: 'damage'
    },


    // === MONK ===
    swift_step: {
        class: 'monk',
        id: 'swift_step',
        tier: 1,
        name: 'Swift Step',
        desc: 'Movement animation 30% faster.',
        icon: images.swift_step_monk,
        cooldown: 0,
        type: 'passive',
        treePath: 'global',
        isPassive: true,
        knownByDefault: true
    },
    focused_rest: {
        class: 'monk',
        id: 'focused_rest',
        tier: 2,
        name: 'Focused Rest',
        desc: 'Camping duration -30% (same healing).',
        icon: images.camp,
        cooldown: 0,
        type: 'passive',
        treePath: 'global',
        isPassive: true,
        knownByDefault: false
    },
    pressure_points: {
        class: 'monk',
        id: 'pressure_points',
        tier: 3,
        name: 'Pressure Points',
        desc: '15% vendor discount once per vendor.',
        icon: images.pressure_points_monk,
        cooldown: 0,
        type: 'passive',
        treePath: 'global',
        isPassive: true,
        knownByDefault: false
    },
    astral_map: {
        class: 'monk',
        id: 'astral_map',
        tier: 4,
        name: 'Astral Map',
        desc: 'Full fog reveal for 60s once per run.',
        icon: images.astral_map_monk,
        cooldown: 0,
        type: 'passive',
        treePath: 'global',
        isPassive: true,
        knownByDefault: false
    },
    monk_ethereal_speed: {
        class: 'monk',
        treePath: 'combat_a',
        id: 'monk_ethereal_speed',
        tier: 1,
        knownByDefault: true,
        name: 'Ethereal Speed',
        desc: 'Flow like wind, gaining extreme speed.',
        icon: images['monk_ethereal_speed'],
        cooldown: 6,
        duration: 'short',
        range: 'self',
        type: 'buff',
        effect: ['buff_self']
    },
    monk_astral_focus: {
        class: 'monk',
        treePath: 'combat_b',
        id: 'monk_astral_focus',
        tier: 3,
        name: 'Astral Focus',
        desc: 'Enter astral focus, boosting concentration.',
        icon: images['monk_astral_focus'],
        cooldown: 12,
        duration: 'short',
        range: 'self',
        type: 'buff'
    },
    monk_astral_projection: {
        class: 'monk',
        treePath: 'combat_b',
        id: 'monk_astral_projection',
        tier: 3,
        name: 'Astral Projection',
        desc: 'Project spirit forward to strike.',
        icon: images['monk_astral_projection'],
        cooldown: 4,
        duration: 'instant',
        range: 'medium',
        atkPercentage: 100,
        type: 'damage'
    },
    monk_force_punch_flurry: {
        class: 'monk',
        treePath: 'combat_b',
        id: 'monk_force_punch_flurry',
        tier: 2,
        name: 'Force Punch Flurry',
        desc: 'Unleash a flurry of force punches.',
        icon: images['monk_force_punch_flurry'],
        cooldown: 6,
        duration: 'instant',
        range: 'close',
        atkPercentage: 100,
        type: 'damage'
    },
    monk_third_eye: {
        class: 'monk',
        treePath: 'combat_b',
        id: 'monk_third_eye',
        tier: 3,
        name: 'Third Eye',
        desc: 'Open third eye, doubling evasion.',
        icon: images['monk_third_eye'],
        cooldown: 10,
        duration: 'short',
        range: 'self',
        type: 'buff'
    },
    monk_twin_finger_authority: {
        class: 'monk',
        treePath: 'combat_a',
        id: 'monk_twin_finger_authority',
        tier: 3,
        name: 'Twin Finger Authority',
        desc: 'Strike critical chakra points, stunning and weakening the target\'s resolve.',
        icon: images['monk_twin_finger_authority'],
        cooldown: 8,
        duration: 'short',
        range: 'close',
        atkPercentage: 100,
        type: 'damage/debuff',
        mentalityDebuff: true,
        power: 45,
        effect: { type: 'twin_finger_stun', duration: '3-rounds', atkReductionPercent: 20 }
    },
    monk_inner_fire: {
        class: 'monk',
        treePath: 'combat_a',
        id: 'monk_inner_fire',
        tier: 4,
        name: 'Inner Fire',
        desc: 'Awaken the inner blaze for fiery attacks.',
        icon: images['monk_inner_fire'],
        cooldown: 12,
        duration: 'long',
        range: 'self',
        type: 'buff',
        effect: ['buff_self'],
        buff: {
            increase_stats: {
                stats: ['atk'],
                amounts: [10]
            }
        }
    },
    monk_meditate: {
        class: 'monk',
        treePath: 'combat_a',
        id: 'monk_meditate',
        tier: 1,
        knownByDefault: true,
        name: 'Meditate',
        desc: 'Restores chi and heals deep wounds.',
        icon: images['monk_meditate'],
        cooldown: 8,
        duration: 'instant',
        range: 'self',
        type: 'heal',
        flatDamage: -25
    },
    monk_whirlwind: {
        class: 'monk',
        treePath: 'combat_b',
        id: 'monk_whirlwind',
        tier: 2,
        name: 'Whirlwind',
        desc: 'Attack all adjacent units in a spin.',
        icon: images['monk_whirlwind'],
        cooldown: 6,
        duration: 'instant',
        range: 'close',
        atkPercentage: 100,
        type: 'damage'
    },
    monk_force_punch: {
        class: 'monk',
        treePath: 'combat_b',
        id: 'monk_force_punch',
        tier: 1,
        knownByDefault: true,
        name: 'Force Punch',
        desc: 'Concentrate force to strike.',
        icon: images['monk_force_punch'],
        cooldown: 2,
        duration: 'instant',
        range: 'close',
        atkPercentage: 100,
        type: 'damage'
    },
    monk_flurry: {
        class: 'monk',
        treePath: 'combat_b',
        id: 'monk_flurry',
        tier: 1,
        knownByDefault: true,
        name: 'Flurry',
        desc: 'Unleash a rapid flurry of strikes.',
        icon: images['monk_flurry'],
        cooldown: 2,
        duration: 'instant',
        range: 'close',
        atkPercentage: 100,
        type: 'damage'
    },
    monk_punch: {
        class: 'monk',
        treePath: 'combat_b',
        id: 'monk_punch',
        tier: 1,
        knownByDefault: true,
        name: 'Punch',
        desc: 'Deliver a powerful, centered chi punch.',
        icon: images['monk_punch'],
        cooldown: 0,
        duration: 'instant',
        range: 'close',
        atkPercentage: 100,
        type: 'damage'
    },

    // === SUMMONER ===
    spirit_sight: {
        class: 'summoner',
        id: 'spirit_sight',
        tier: 1,
        name: 'Spirit Sight',
        desc: 'Narrative tiles glow through fog.',
        icon: images.spirit_sight_summoner,
        cooldown: 0,
        type: 'passive',
        treePath: 'global',
        isPassive: true,
        knownByDefault: true
    },
    plunder: {
        class: 'summoner',
        id: 'plunder',
        tier: 2,
        name: 'Plunder',
        desc: 'Open a chest a second time once per run.',
        icon: images.plunder_summoner,
        cooldown: 0,
        type: 'passive',
        treePath: 'global',
        isPassive: true,
        knownByDefault: false
    },
    soul_tithe: {
        class: 'summoner',
        id: 'soul_tithe',
        tier: 3,
        name: 'Soul Tithe',
        desc: '+1 Shimmering Dust per combat victory.',
        icon: images.soul_tithe_summoner,
        cooldown: 0,
        type: 'passive',
        treePath: 'global',
        isPassive: true,
        knownByDefault: false
    },
    dark_pact: {
        class: 'summoner',
        id: 'dark_pact',
        tier: 4,
        name: 'Dark Pact',
        desc: 'Trade Shimmering Dust at vendors (1 Dust = 25g).',
        icon: images.dark_pact_summoner,
        cooldown: 0,
        type: 'passive',
        treePath: 'global',
        isPassive: true,
        knownByDefault: false
    },
    open_rift: {
        class: 'summoner',
        treePath: 'combat_b',
        id: 'open_rift',
        tier: 3,
        name: 'Open the Rift',
        desc: 'Summon a rift portal for 3 long durations.',
        icon: images['open_rift_icon'],
        cooldown: 12,
        duration: '3x-long',
        range: 'medium',
        type: 'utility'
    },
    summon_skeleton: {
        class: 'summoner',
        treePath: 'combat_a',
        id: 'summon_skeleton',
        tier: 1,
        knownByDefault: true,
        name: 'Summon Skeleton',
        desc: 'Summon a skeleton warrior to the field (L1: Max 2 skeletons; L2: Max 3; L3: Skeletons have 2x HP and 2x attack damage).',
        icon: images['summon_skeleton_icon'],
        cooldown: 7,
        initialCount: 3,
        duration: 'instant',
        range: 'medium',
        type: 'utility'
    },
    summon_imp: {
        class: 'summoner',
        treePath: 'combat_b',
        id: 'summon_imp',
        tier: 1,
        knownByDefault: true,
        name: 'Summon Imp',
        desc: 'Summon a fiery imp minion (L1: Max 2 imps; L2: Max 3; L3: Imps have 2x Speed and +20% physical miss chance).',
        icon: images['summon_imp_icon'],
        cooldown: 8,
        initialCount: 1,
        duration: 'instant',
        range: 'medium',
        type: 'utility'
    },
    summon_skeleton_knight: {
        class: 'summoner',
        treePath: 'combat_a',
        id: 'summon_skeleton_knight',
        tier: 2,
        name: 'Summon Skeleton Knight',
        desc: 'Summon a heavily armored skeleton knight.',
        icon: images['summon_skeleton_knight_icon'],
        cooldown: 10,
        duration: 'instant',
        range: 'medium',
        type: 'utility'
    },
    summon_zombie: {
        class: 'summoner',
        treePath: 'combat_a',
        id: 'summon_zombie',
        tier: 2,
        name: 'Summon Zombie',
        desc: 'Summon a plague-carrying zombie.',
        icon: images['summon_zombie_icon'],
        cooldown: 10,
        duration: 'instant',
        range: 'medium',
        type: 'utility'
    },
    summon_ghoul: {
        class: 'summoner',
        treePath: 'combat_a',
        id: 'summon_ghoul',
        tier: 2,
        name: 'Summon Ghoul',
        desc: 'Summon a ravenous flesh-eating ghoul.',
        icon: images['summon_ghoul_icon'],
        cooldown: 10,
        duration: 'instant',
        range: 'medium',
        type: 'utility'
    },
    summon_imp_army: {
        class: 'summoner',
        treePath: 'combat_b',
        id: 'summon_imp_army',
        tier: 3,
        name: 'Summon Imp Army',
        desc: 'Summon a swarm of imp minions.',
        icon: images['summon_imp_army_icon'],
        cooldown: 14,
        duration: 'instant',
        range: 'medium',
        type: 'utility'
    },
    summon_skeleton_army: {
        class: 'summoner',
        treePath: 'combat_a',
        id: 'summon_skeleton_army',
        tier: 3,
        name: 'Summon Skeleton Army',
        desc: 'Summon a legion of skeleton warriors.',
        icon: images['summon_skeleton_army_icon'],
        cooldown: 14,
        duration: 'instant',
        range: 'medium',
        type: 'utility'
    },
    summon_devil: {
        class: 'summoner',
        treePath: 'combat_b',
        id: 'summon_devil',
        tier: 4,
        name: 'Summon Devil',
        desc: 'Summon a high devil minion.',
        icon: images['summon_devil_icon'],
        cooldown: 16,
        duration: 'instant',
        range: 'medium',
        type: 'utility'
    },
    summoner_duplicate: {
        class: 'summoner',
        treePath: 'combat_b',
        id: 'summoner_duplicate',
        tier: 1,
        knownByDefault: true,
        name: 'Duplicate',
        desc: 'Create a duplicate of the summoned minion.',
        icon: images['duplicate_icon'],
        cooldown: 10,
        initialCooldown: 4,
        duration: 'instant',
        range: 'medium',
        type: 'utility'
    },
    summoner_triplicate: {
        class: 'summoner',
        treePath: 'combat_b',
        id: 'summoner_triplicate',
        tier: 3,
        name: 'Triplicate',
        desc: 'Create two duplicates of the summoned minion.',
        icon: images['triplicate_icon'],
        cooldown: 8,
        duration: 'instant',
        range: 'medium',
        type: 'utility'
    },
    dominate_minion: {
        class: 'summoner',
        treePath: 'combat_a',
        id: 'dominate_minion',
        tier: 3,
        name: 'Dominate Minion',
        desc: 'Exert your will upon an enemy minion. Pit your INT against their willpower — on success, the minion switches sides and fights for you.',
        icon: images['dominate_minion_icon'],
        cooldown: 10,
        initialCooldown: 4,
        duration: 'instant',
        range: 'far',
        type: 'debuff',
        effect: { type: 'dominate', willpowerCheck: true }
    },

    // === MONSTERS ===
    // Goblin
    goblin_slash: {
        id: 'goblin_slash',
        tier: 1,
        name: 'Slash',
        desc: 'Execute a claw strike.',
        icon: images['claw_strike'],
        cooldown: 0,
        duration: 'instant',
        range: 'close',
        atkPercentage: 100,
        type: 'damage'
    },
    goblin_bite: {
        id: 'goblin_bite',
        tier: 1,
        name: 'Bite',
        desc: 'Savage bite attack.',
        icon: images['monster_bite'],
        cooldown: 4,
        duration: 'short',
        range: 'close',
        atkPercentage: 100,
        type: 'damage',
        effect: { type: 'bleed', chance: 100, duration: 'short' }
    },
    claw_strike: {
        id: 'claw_strike',
        tier: 1,
        name: 'Claw Strike',
        desc: 'Execute a savage claw strike.',
        icon: images['claw_strike'],
        cooldown: 2,
        duration: 'instant',
        range: 'close',
        atkPercentage: 100,
        type: 'damage'
    },
    sword_swing: {
        id: 'sword_swing',
        tier: 1,
        knownByDefault: true,
        name: 'Sword Swing',
        desc: 'Execute a sword swing.',
        icon: images['shortsword'],
        cooldown: 1,
        duration: 'instant',
        range: 'close',
        atkPercentage: 100,
        type: 'damage'
    },
    bite: {
        id: 'bite',
        tier: 1,
        name: 'Bite',
        desc: 'Savage bite attack.',
        icon: images['monster_bite'],
        cooldown: 4,
        duration: 'short',
        range: 'close',
        atkPercentage: 100,
        type: 'damage',
        effect: { type: 'bleed', chance: 40, duration: 'short' }
    },
    regenerate: {
        id: 'regenerate',
        tier: 2,
        name: 'Regenerate',
        desc: 'Heal 5 HP per round for 10 rounds.',
        icon: images.regenerate,
        cooldown: 20,
        duration: '10-rounds',
        range: 'self',
        type: 'heal',
        effect: ['heal_self']
    },
    sacrificial_mending: {
        id: 'sacrificial_mending',
        tier: 2,
        name: 'Sacrificial Mending',
        desc: 'Drain 20 HP from self and grant it to an adjacent aberration ally, then trigger Regenerate on the recipient.',
        icon: images.blalok_sacrificial_mending,
        cooldown: 8,
        initialCooldown: 4,
        duration: 'instant',
        range: 'close',
        type: 'heal',
        // Handled entirely by bespoke logic in _aiBlalok / useAbility.
        // Only usable when an aberration/blalok ally is in close range.
        effect: ['sacrificial_mending']
    },
    gore: {
        id: 'gore',
        tier: 2,
        name: 'Gore',
        desc: 'Savage strike dealing 200% ATK damage with a 70% chance to cause bleeding.',
        icon: images.gore,
        cooldown: 4,
        duration: 'short',
        range: 'close',
        atkPercentage: 200,
        type: 'damage',
        effect: { type: 'bleed', chance: 70, duration: 'short' }
    },
    despair: {
        id: 'despair',
        tier: 2,
        name: 'Despair',
        desc: "Unleash a wave of darkness that drains 30 stamina (endurance) from all enemies, and reduces the crew's resolve by 20 points.",
        icon: images['shadow_presence'],
        cooldown: 8,
        duration: 'instant',
        range: 'far',
        type: 'debuff'
    },
    // Skeleton
    reassembly: {
        id: 'reassembly',
        tier: 1,
        name: 'Reassembly',
        desc: 'Collapse and reassemble upon death (50% chance to trigger).',
        icon: images['reassembly'],
        cooldown: 12,
        duration: 'long',
        range: 'self',
        type: 'passive',
        isPassive: true
    },
    bifurcate: {
        id: 'bifurcate',
        tier: 1,
        name: 'Bifurcate',
        desc: 'At full energy, split into two smaller copies, each with 50% of current HP.',
        icon: images['bifurcate'],
        cooldown: 0,
        duration: 'instant',
        range: 'self',
        type: 'utility'
    },
    minor_magic_missile: {
        id: 'minor_magic_missile',
        tier: 1,
        name: 'Minor Magic Missile',
        desc: 'Shoot a small magic missile at a target.',
        icon: images['magic_missile_icon'],
        cooldown: 4,
        duration: 'instant',
        range: 'far',
        atkPercentage: 100,
        type: 'damage'
    },
    // Mummy
    induce_fear: {
        id: 'induce_fear',
        tier: 1,
        name: 'Induce Fear',
        desc: 'Scream, filling targets with dread. Reduces ATK and DEF.',
        icon: images['induce_fear'],
        cooldown: 16,
        duration: 'short',
        range: 'medium',
        type: 'debuff',
        mentalityDebuff: true,
        power: 30,
        effect: { type: 'fear', duration: 'short', atkReductionPercent: 30, defReductionPercent: 30 }
    },
    energy_drain: {
        id: 'energy_drain',
        tier: 1,
        name: 'Energy Drain',
        desc: 'Drain vitality from target at range.',
        icon: images['energy_drain'],
        cooldown: 6,
        duration: 'short',
        range: 'medium',
        type: 'debuff',
        effect: { type: 'drain', chance: 100 }
    },
    // Ogre
    stomp: {
        id: 'stomp',
        tier: 1,
        name: 'Stomp',
        desc: 'Leap and slam, stunning adjacent units.',
        icon: images['stomp'],
        cooldown: 8,
        duration: 'short',
        range: 'close',
        atkPercentage: 100,
        type: 'damage',
        effect: { type: 'stun', chance: 100, duration: 'short' }
    },
    head_butt: {
        id: 'head_butt',
        tier: 1,
        name: 'Headbutt',
        desc: 'Powerful headbutt pushing target back.',
        icon: images['head_butt'],
        cooldown: 6,
        duration: 'instant',
        range: 'close',
        atkPercentage: 100,
        type: 'damage'
    },
    // Vampire
    vampiric_bite: {
        id: 'vampiric_bite',
        tier: 1,
        name: 'Vampiric Bite',
        desc: 'Savage bite that drains vitality.',
        icon: images['vampiric_bite'],
        cooldown: 4,
        duration: 'instant',
        range: 'close',
        atkPercentage: 100,
        type: 'damage',
        flatDamage: 15,
        effect: { type: 'bleed', chance: 100, duration: 'medium' }
    },
    bat_fly: {
        id: 'bat_fly',
        tier: 1,
        name: 'Bat Fly',
        desc: 'Transform into bats to relocate.',
        icon: images['bat_fly'],
        cooldown: 8,
        duration: 'instant',
        range: 'far',
        type: 'utility'
    },
    crimson_sight: {
        id: 'crimson_sight',
        tier: 1,
        name: 'Crimson Sight',
        desc: 'Pierce the target\'s mind, exposing critical vulnerabilities and reducing their defense.',
        icon: images['crimson_sight'],
        cooldown: 10,
        duration: 'short',
        range: 'medium',
        type: 'debuff',
        mentalityDebuff: true,
        power: 25,
        effect: { type: 'crimson_sight', duration: '3-rounds', defReductionPercent: 40 }
    },
    soul_suck: {
        id: 'soul_suck',
        tier: 3,
        name: 'Soul Suck',
        desc: 'Drain target\'s soul energy.',
        icon: images['soul_suck'],
        cooldown: 12,
        duration: 'short',
        range: 'medium',
        atkPercentage: 100,
        type: 'damage/debuff',
        effect: { type: 'stun', chance: 10, duration: 'long' }
    },
    // Djinn
    betrayal: {
        id: 'betrayal',
        tier: 1,
        name: 'Betrayal',
        desc: 'Sow discord in the target\'s mind, forcing them to switch sides and fight their allies.',
        icon: images['betrayal'],
        cooldown: 12,
        duration: 'short',
        range: 'medium',
        type: 'debuff',
        mentalityDebuff: true,
        power: 50,
        effect: { type: 'betrayal', duration: 'long' }
    },
    arcane_barrier: {
        id: 'arcane_barrier',
        tier: 1,
        name: 'Arcane Barrier',
        desc: 'Shield in pure arcane force. Active for 4 rounds, any spells or projectiles targeting the unit have a 50% chance to fail completely (checked before all other checks).',
        icon: images['arcane_barrier'],
        cooldown: 10,
        duration: 'long',
        range: 'self',
        type: 'buff',
        effect: { type: 'arcane_barrier', duration: 'long' }
    },
    death_missile: {
        id: 'death_missile',
        tier: 1,
        name: 'Death Missile',
        desc: 'Fires skull missile that curses target.',
        icon: images['death_missile'],
        cooldown: 8,
        duration: 'short',
        range: 'far',
        type: 'debuff damage',
        flatDamage: 10,
        atkPercentage: 120,
        effect: { type: 'instant_death', chance: 15 }
    },
    bind: {
        id: 'bind',
        tier: 1,
        name: 'Bind',
        desc: 'Restrict target movement with psychic shackles.',
        icon: images['bind'],
        cooldown: 8,
        duration: 'short',
        range: 'medium',
        type: 'debuff',
        mentalityDebuff: true,
        power: 35,
        effect: { type: 'ensnared', duration: 'medium' }
    },
    rift: {
        id: 'rift',
        tier: 1,
        name: 'Rift',
        desc: 'Conjure a jagged line of energy spanning three vertical tiles in front of you. After a brief delay, the line surges outward, pushing back any units caught in its path by two tiles.',
        icon: images['djinn_rift'],
        cooldown: 12,
        range: 'close',
        type: 'utility',
        initialCooldown: 3,
    },
    // ── Sphinx skills ────────────────────────────────────────────────────────
    third_eye: {
        id: 'third_eye',
        tier: 1,
        name: 'Third Eye',
        desc: 'Chance to dodge incoming physical attacks.',
        icon: images['third_eye'],
        cooldown: 6,
        duration: 'medium',
        range: 'self',
        type: 'buff',
    },
    polymorph: {
        id: 'polymorph',
        tier: 2,
        name: 'Polymorph',
        desc: 'Transform the target into a helpless frog for a long duration.',
        icon: images['polymorph'],
        cooldown: 12,
        duration: 'long',
        range: 'medium',
        type: 'debuff',
        mentalityDebuff: true,
        power: 60,
    },
    hex: {
        class: 'witch',
        id: 'hex',
        tier: 2,
        name: 'Hex',
        desc: 'Curse the target for 4 rounds. Reduces ATK by 2 and gives all skill uses a 35% chance to backfire, failing the action and dealing 10 damage to the caster.',
        icon: images['hex'],
        cooldown: 10,
        duration: 'medium',
        range: 'far',
        type: 'debuff',
        mentalityDebuff: true,
        power: 45,
    },
    begin_the_trials: {
        id: 'begin_the_trials',
        tier: 3,
        name: 'Begin the Trials',
        desc: 'Unleash the Trials of the Sphinx. Summons a mystical trial icon that attacks fighters with willpower-sapping beams.',
        icon: images['begin_trials'],
        cooldown: 22,
        duration: 'long',
        range: 'self',
        type: 'begin_trials_type',
        mentalityDebuff: true,
        power: 55
    },
    shadow_armor: {
        id: 'shadow_armor',
        tier: 2,
        name: 'Shadow Armor',
        desc: 'Passive: 15% physical damage reduction. 35% chance each round to dispel debuffs.',
        icon: images['shadow_armor'],
        type: 'passive',
        isPassive: true
    },
    nether_bolt: {
        id: 'nether_bolt',
        tier: 2,
        name: 'Nether Bolt',
        desc: 'Fire a projectile dealing 115% ATK + 8 flat damage with a 40% chance to inflict fear.',
        icon: images['nether_bolt'],
        cooldown: 8,
        initialCooldown: 2,
        range: 'medium',
        type: 'damage',
        atkPercentage: 115,
        flatBonus: 8,
        effect: { type: 'fear', chance: 40, duration: 'medium' }
    },
    invoke_darkness: {
        id: 'invoke_darkness',
        tier: 2,
        name: 'Invoke Darkness',
        desc: 'Summon an unkillable black sphere adjacent that deals 5 damage to adjacent enemies and swallows projectiles.',
        icon: images['invoke_darkness'],
        cooldown: 12,
        range: 'self',
        type: 'summon'
    },
    undead_grasp: {
        id: 'undead_grasp',
        tier: 1,
        name: 'Undead Grasp',
        desc: 'Savage close-range claw strike dealing 100% ATK damage with a 20% chance to stun.',
        icon: images['undead_grasp'],
        cooldown: 4,
        range: 'close',
        type: 'damage',
        atkPercentage: 100,
        effect: { type: 'stun', chance: 20, duration: 'short' }
    },
    shadow_curse: {
        class: 'witch',
        id: 'shadow_curse',
        tier: 3,
        name: 'Shadow Curse',
        desc: 'Curse the target for 4 rounds. While active, the stamina (endurance) cost of any movement or action is tripled (increased from 2 to 6). If stamina drops to 0, the unit is immediately exhausted, falling asleep and becoming stunned for 4 rounds.',
        icon: images['shadow_curse'],
        cooldown: 12,
        duration: 'long',
        range: 'far',
        type: 'debuff',
        effect: { type: 'shadow_curse', duration: 'long' }
    },
    greater_magic_missile: {
        class: 'witch',
        id: 'greater_magic_missile',
        tier: 2,
        name: 'Greater Magic Missile',
        desc: 'Shoot a large, high-velocity magic missile that deals heavy damage.',
        icon: images['magic_missile_icon'],
        cooldown: 5,
        duration: 'instant',
        range: 'far',
        atkPercentage: 100,
        type: 'damage',
        initialCooldown: 3
    },
    spiderweb: {
        class: 'witch',
        id: 'spiderweb',
        tier: 2,
        name: 'Spiderweb',
        desc: 'Ensnare the target in a sticky web, preventing movement.',
        icon: images['spiderweb'],
        cooldown: 8,
        duration: 'short',
        range: 'far',
        type: 'debuff',
        effect: { type: 'ensnared', duration: 'short' }
    },
    summon_spiders: {
        class: 'witch',
        id: 'summon_spiders',
        tier: 3,
        name: 'Summon Spiders',
        desc: 'Summon giant spiders to assist in combat.',
        icon: images['summon_spiders_icon'],
        cooldown: 12,
        duration: 'instant',
        range: 'medium',
        type: 'utility',
        initialCooldown: 1
    },
    dispell: {
        class: 'witch',
        id: 'dispell',
        tier: 3,
        name: 'Dispell',
        desc: 'Dispel active magical effects from targets.',
        icon: images['witch_dispell'],
        cooldown: 10,
        duration: 'instant',
        range: 'far',
        type: 'utility'
    },
    demonic_whispers: {
        class: 'witch',
        id: 'demonic_whispers',
        tier: 3,
        name: 'Demonic Whispers',
        desc: "Sow madness in the target's mind, causing fear.",
        icon: images['demonic_whispers'],
        cooldown: 10,
        duration: 'short',
        range: 'far',
        type: 'debuff',
        effect: { type: 'fear', duration: 'short' }
    },
    transform: {
        id: 'transform',
        tier: 3,
        name: 'Transform',
        desc: 'Transform into a dark beast, increasing attack power.',
        icon: images['transform'],
        cooldown: 18,
        duration: 'long',
        range: 'self',
        type: 'buff',
        effect: ['buff_self'],
        chargingRounds: 2,
        demonRounds: 5,
        buff: {
            increase_stats: {
                stats: ['atk'],
                amounts: [8]
            }
        }
    },
    dragon_whirlwind: {
        id: 'dragon_whirlwind',
        tier: 3,
        name: 'Whirlwind',
        desc: 'Unleash a massive windstorm pushing back nearby enemies.',
        icon: images['whirlwind'],
        cooldown: 10,
        initialCooldown: 0,
        duration: 'instant',
        range: 'self',
        type: 'dragon_whirlwind_type'
    },
    bombard: {
        id: 'bombard',
        tier: 4,
        name: 'Bombard',
        desc: 'Bombard the enemy from above after a 1-round delay.',
        icon: images['bombard'],
        cooldown: 12,
        initialCooldown: 0,
        duration: 'long',
        range: 'medium',
        type: 'bombard_type'
    },
    dragon_dispell: {
        id: 'dragon_dispell',
        tier: 3,
        name: 'Dispell',
        desc: 'Dispel active magical effects from targets.',
        icon: images['dispell'],
        cooldown: 10,
        initialCooldown: 0,
        duration: 'instant',
        range: 'medium',
        type: 'dispell_type'
    },
    lay_eggs: {
        id: 'lay_eggs',
        tier: 3,
        name: 'Lay Eggs',
        desc: 'Lay a dragon egg adjacent to the dragon that hatches into an ally minion after 6 rounds.',
        icon: images['lay_eggs'],
        cooldown: 8,
        initialCooldown: 2,
        duration: 'instant',
        range: 'close',
        type: 'lay_eggs_type'
    },
    blue_dragon_breath: {
        id: 'blue_dragon_breath',
        tier: 3,
        name: 'Blue Dragon Breath',
        desc: 'Breathe a cone of fire dealing damage to all targets in a medium range.',
        icon: images['blue_dragon_breath'],
        cooldown: 4,
        duration: 'instant',
        range: 'medium',
        atkPercentage: 100,
        type: 'damage',
        flatDamage: 25
    },
    rake: {
        id: 'rake',
        name: 'Rake',
        desc: 'Execute a claw strike with a 50% chance to strike again after 0.75 seconds.',
        icon: images.rake,
        cooldown: 2,
        duration: 'instant',
        range: 'close',
        atkPercentage: 100,
        type: 'damage'
    },
    silence: {
        id: 'silence',
        name: 'Silence',
        desc: 'Prevent casting magic users from using skills for a short duration.',
        icon: images.silence,
        cooldown: 6,
        initialCooldown: 4,
        duration: 'short',
        range: 'medium',
        type: 'debuff'
    },
    gore_horns: {
        id: 'gore_horns',
        name: 'Gore Horns',
        desc: 'Lunge and hit the target for 200% attack damage, with a 60% chance to bleed.',
        icon: images.gore_horns,
        cooldown: 4,
        duration: 'instant',
        range: 'close',
        type: 'damage',
        atkPercentage: 200,
        effect: { type: 'bleed', chance: 60, duration: 'medium' }
    },
    demon_mark: {
        id: 'demon_mark',
        name: 'Demon Mark',
        desc: 'Mark all enemies, increasing damage taken from demons by 50% for a long duration.',
        icon: images.demon_mark,
        cooldown: 6,
        duration: 'long',
        range: 'all',
        type: 'debuff'
    },
    new_moon: {
        id: 'new_moon',
        name: 'New Moon',
        desc: 'All demons gain +40% Attack (+60% for demon kids) and melee attacks have a 40% (50% for demon kids) chance to fear enemies for a short duration.',
        icon: images.new_moon,
        cooldown: 6,
        duration: 'long',
        range: 'self',
        type: 'buff'
    },
    malevolent_presence: {
        id: 'malevolent_presence',
        name: 'Malevolent Presence',
        desc: 'Passive: Adjacent enemies at round start have a 20% chance to be feared for a short duration.',
        icon: images.malevolent_presence,
        type: 'passive',
        isPassive: true
    },
    dominate: {
        id: 'dominate',
        name: 'Dominate',
        desc: 'Cast a dominate spell on a crew member for 2 rounds. Upon expiration, the target makes a contested willpower check to break free; on failure, they remain dominated for 1 more round.',
        icon: images.hashmallim_dominate,
        cooldown: 15,
        initialCooldown: 4,
        duration: 2,
        range: 'far',
        type: 'debuff',
        effect: { type: 'dominate', duration: 2 }
    },
    madness: {
        id: 'madness',
        name: 'Madness',
        desc: 'Project a fracturing psychic field into a 2×2 area, pitting the Hashmallim\'s terrible will against the minds of all within. Those who fail the contested mentality check are consumed by the Madness debuff for 10 eras — each round they have a 50% chance to switch sides and attack their own allies in a fit of uncontrollable violence, and a 25% chance to turn on themselves, dealing self-inflicted damage in a moment of psychotic rage.',
        icon: images.hashmallim_madness,
        cooldown: 14,
        initialCooldown: 6,
        duration: 'long',
        range: 'medium',
        type: 'debuff',
        effect: { type: 'madness', duration: 'long' }
    },
    overload: {
        id: 'overload',
        name: 'Overload',
        desc: 'Unleash energy dealing raw damage equal to stamina used so far (max - current). Bypasses defense. If target is above 50% stamina, splits damage between HP and stamina, otherwise deals full damage to HP.',
        icon: images.hashmallim_overload,
        cooldown: 8,
        initialCooldown: 2,
        duration: 'instant',
        range: 'medium',
        type: 'damage'
    },
    meteors: {
        id: 'meteors',
        name: 'Meteors',
        desc: 'Strike 3 delayed tiles dealing 120% ATK damage after 1 round. Uses a white/orange visual theme.',
        icon: images.hashmallim_meteors,
        cooldown: 8,
        initialCooldown: 4,
        duration: 'instant',
        range: 'far',
        type: 'damage'
    },
    entropic_kindred: {
        id: 'entropic_kindred',
        name: 'Entropic Kindred',
        desc: 'Once per combat: Add three empty columns to the center of the board, pushing the monster and minion units right to distance them from enemies.',
        icon: images.hashmallim_entropic_kindred,
        cooldown: 15,
        initialCooldown: 10,
        duration: 'instant',
        range: 'far',
        type: 'utility'
    },

    // ── Hagigah skills ──────────────────────────────────────────────────────
    destitution: {
        id: 'destitution',
        name: 'Destitution',
        desc: 'Drain all enemies of 50% of their current stamina and convert it into raw damage bypassing defense.',
        icon: images['hagigah_destitution'],
        cooldown: 10,
        initialCooldown: 3,
        duration: 'instant',
        range: 'all',
        type: 'damage'
    },
    hagigah_spineskin: {
        id: 'hagigah_spineskin',
        name: 'Spineskin',
        desc: 'Hagigah sprouts a dense layer of bone spines. For 3 rounds, any melee attack against Hagigah deals 25% of its own raw damage back to the attacker.',
        icon: images['hagigah_spineskin'],
        cooldown: 10,
        initialCooldown: 5,
        duration: 'short',
        range: 'self',
        type: 'buff'
    },
    summon_skulls: {
        id: 'summon_skulls',
        name: 'Summon Skulls',
        desc: 'Conjure 1–2 flaming skull minions on adjacent free tiles.',
        icon: images['hagigah_summon_skulls'],
        cooldown: 8,
        initialCooldown: 2,
        duration: 'instant',
        range: 'self',
        type: 'utility'
    },

    // ── Beholder skills ─────────────────────────────────────────────────────
    chainbolt: {
        id: 'chainbolt',
        name: 'Chainbolt',
        desc: 'Fires a white energy beam that chains through every PC unit on the board. Each link deals 125% ATK damage.',
        icon: images['beholder_chainbolt'],
        cooldown: 6,
        initialCooldown: 2,
        duration: 'instant',
        range: 'far',
        atkPercentage: 125,
        type: 'damage'
    },
    mind_swap: {
        id: 'mind_swap',
        name: 'Mind Swap',
        desc: 'Fires a purple psychic beam at one PC unit; the beam then jumps to the farthest PC unit on the board. The two targets swap positions.',
        icon: images['beholder_mindswap'],
        cooldown: 10,
        initialCooldown: 1,
        duration: 'instant',
        range: 'far',
        type: 'utility'
    },
    displacement_ray: {
        id: 'displacement_ray',
        name: 'Displacement Ray',
        desc: 'Fires a destabilising ray that deals 80% ATK damage and pushes the target 2 tiles away from the Beholder.',
        icon: images['beholder_displacement_ray'],
        cooldown: 5,
        initialCooldown: 1,
        duration: 'instant',
        range: 'far',
        atkPercentage: 80,
        type: 'damage',
        mentalityCheck: true
    },
    invisibility: {
        id: 'invisibility',
        name: 'Invisibility',
        desc: 'The Beholder fades from sight, becoming invisible and gaining a 40% chance to dodge attacks for a medium duration.',
        icon: images['beholder_invisibility'],
        cooldown: 12,
        initialCooldown: 3,
        duration: 'medium',
        range: 'self',
        type: 'buff'
    },
    voidbite: {
        id: 'voidbite',
        name: 'Voidbite',
        desc: 'A savage maw strike at close range dealing 150% ATK damage and draining 30% of dealt damage as stamina from the target.',
        icon: images['beholder_voidbite'],
        cooldown: 4,
        duration: 'instant',
        range: 'close',
        atkPercentage: 150,
        type: 'damage',
        effect: { type: 'drain', duration: 'instant' }
    },
    void_rake: {
        id: 'void_rake',
        name: 'Void Rake',
        desc: "Execute a claw strike with a 50% chance to strike again after 0.75 seconds. Deals 200% ATK damage and has a 30% chance to teleport the target to a random corner of the board.",
        icon: images.void_rake,
        cooldown: 4,
        initialCooldown: 1,
        duration: 'instant',
        range: 'close',
        atkPercentage: 200,
        type: 'damage'
    },
    eldritch_wind: {
        id: 'eldritch_wind',
        name: 'Eldritch Wind',
        desc: "Fully restores the stamina of all friendly units and restores 10% of their max HP.",
        icon: images.eldritch_wind,
        cooldown: 10,
        initialCooldown: 4,
        duration: 'instant',
        range: 'self',
        type: 'heal'
    },
    paradox_engine: {
        id: 'paradox_engine',
        name: 'Paradox Engine',
        desc: "Teleports the target unit to an unoccupied corner, locking them in place facing the center, confronted by an upside-down red pulsing reflection of themselves. The target is stationary and takes 50% of the caster's ATK each round. Mentality check at the end determines if it lasts 2 more rounds.",
        icon: images.paradox_engine,
        cooldown: 10,
        initialCooldown: 6,
        duration: 3,
        range: 'far',
        type: 'debuff'
    }
};

export default skillsMatrix;

